name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
#    - name: Instal IBM Cloud CLI      
#      run: curl -sL https://ibm.biz/idt-installer | bash
#    - name: Install IBM Cloud Foundry CLI            
#      run: ibmcloud cf install      
#    - name: Check cf
#      run: bx cf
    - name: Install Cloud Foundry
      run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx        
    - name: Install Cloud Foundry
      run: mv cf /usr/local/bin        
    - name: Install Cloud Foundry
      run: sudo curl -o /usr/share/bash-completion/completions/cf https://raw.githubusercontent.com/cloudfoundry/cli-ci/master/ci/installers/completion/cf
    - name: Confirm Install Cloud Foundry
      run: cf version
          
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
